variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

linux:
  tags:
    - linux
  stage:
    build
  artifacts:
    paths:
    - build/
  script:
    - git submodule update --init --force --recursive
    - rm -rf build
    - mkdir -p build
    - cd build
    - /opt/qt/5.8/gcc_64/bin/qmake -r ../shv.pro DEFINES+=GIT_COMMIT=${CI_BUILD_REF}
    - make -j2

linux-deploy:
  only:
    - master
  tags:
    - linux
  stage:
    deploy
  script:
    - cd build
      #- sudo /opt/eyas/install-eyassrv.sh
  environment:
    name: jessie


