variables:
  GIT_SUBMODULE_STRATEGY: recursive
  SHV_NIRVANA_IP: "165.227.247.202"
  SHV_HEAVEN_IP: "138.68.112.73"

stages:
  - build
  - deploy

linux:
  tags:
    - linux
  stage:
    build
  artifacts:
    paths:
    - build/_dist/
  script:
    #- git submodule update --init --force --recursive
    - rm -rf build
    - mkdir -p build
    - cd build
    - /opt/qt/5.15.2/gcc_64/bin/qmake -r CONFIG+=release CONFIG-=qml_debug CONFIG-=qtquickcompiler CONFIG+=with-shvwebsockets ../shv.pro DEFINES+=GIT_COMMIT=${CI_BUILD_REF}
    - make -j2
    #- rsync -av --exclude '*.debug' lib bin /opt/shv/
    - ../make-linux-artifacts.sh

linux-bb:
  only:
    - production
  tags:
    - beaglebone
  stage:
    build
  artifacts:
    paths:
    - build-bb/lib/
    - build-bb/bin/
  script:
    #- git submodule update --init --force --recursive
    - rm -rf build-bb
    - mkdir -p build-bb
    - cd build-bb
    - /opt/qt512-bbb/bin/qmake -r CONFIG+=no-libshv-gui CONFIG+=beaglebone ../shv.pro DEFINES+=GIT_COMMIT=${CI_BUILD_REF}
    - make -j2

production-deploy:
  only:
    - production
  tags:
    - linux
  stage:
    deploy
  script:
    - id
    - cd build
    # aws
    #- rsync -avz lib bin gitlab-jessie@35.167.83.38:/opt/shv/ 
    #- ssh -t gitlab-jessie@35.167.83.38 "sudo /opt/shv/install.sh"
    # nirvana
    - rsync -avz _dist/lib _dist/bin gitlab@${SHV_NIRVANA_IP}:/opt/shv-prod/ 
    - ssh -t gitlab@${SHV_NIRVANA_IP} "sudo /opt/shv-prod/install.sh"

  environment:
    name: jessie

production-deploy-heaven:
  only:
    - production
  tags:
    - linux
  stage:
    deploy
  script:
    - id
    - cd build
    - rsync -avz _dist/lib _dist/bin shv@${SHV_HEAVEN_IP}:/opt/shv/production/
    - ssh -t shv@${SHV_HEAVEN_IP} "sudo /opt/shv/production/install.sh"
  environment:
    name: heaven

test-deploy:
  only:
    - master
  tags:
    - linux
  stage:
    deploy
  script:
    # nirvana
    - pwd
    #- rsync -avz shvbroker/etc gitlab@${SHV_NIRVANA_IP}:/opt/shv/ 
    #- rsync -avz clients/hscope/etc gitlab@${SHV_NIRVANA_IP}:/opt/shv/ 
    - cd build
    - rsync -avz _dist/lib _dist/bin /opt/shv/ 
    - rsync -avz _dist/lib _dist/bin gitlab@${SHV_NIRVANA_IP}:/opt/shv/ 
    - ssh -t gitlab@${SHV_NIRVANA_IP} "sudo /opt/shv/install.sh"
    # heaven 
    - rsync -avz _dist/lib _dist/bin shv@${SHV_HEAVEN_IP}:/opt/shv/test/
    - ssh -t shv@${SHV_HEAVEN_IP} "sudo /opt/shv/test/install.sh"

  environment:
    name: jessie

#win-build:
#  tags:
#    - windows
#  stage:
#    build
#  script: 
#    - bash build-win.sh
#  artifacts:
#    paths:
#      - _inno/
#
#win-deploy:
#  only:
#    - production
#  tags:
#    - windows
#  stage:
#    deploy
#  script:
#    - cmd /Q /C deploy-win.sh
#  environment:
#    name: claudius

