variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

linux:
  tags:
    - linux
  stage:
    build
  artifacts:
    paths:
    - build/lib/
    - build/bin/
  script:
    #- git submodule update --init --force --recursive
    - rm -rf build
    - mkdir -p build
    - cd build
    - /opt/qt/5.12.0/gcc_64/bin/qmake -r CONFIG+=no-libshv-gui CONFIG+=with-shvwebsockets ../shv.pro DEFINES+=GIT_COMMIT=${CI_BUILD_REF}
    - make -j2
    #- ../make-linux-artifacts.sh

linux-bb:
  tags:
    - beaglebone
  stage:
    build
  artifacts:
    paths:
    - build-bb/lib/
    - build-bb/bin/
  script:
    #- git submodule update --init --force --recursive
    - rm -rf build-bb
    - mkdir -p build-bb
    - cd build-bb
    - /opt/qt5bbb/bin/qmake -r CONFIG+=no-libshv-gui CONFIG+=beaglebone ../shv.pro DEFINES+=GIT_COMMIT=${CI_BUILD_REF}
    - make -j2

production-deploy:
  only:
    - production
  tags:
    - linux
  stage:
    deploy
  script:
    - id
    - cd build
    # aws
    #- rsync -avz lib bin gitlab-jessie@35.167.83.38:/opt/shv/ 
    #- ssh -t gitlab-jessie@35.167.83.38 "sudo /opt/shv/install.sh"
    # nirvana
    - rsync -avz lib bin gitlab@165.227.247.202:/opt/shv-prod/ 
    - ssh -t gitlab@165.227.247.202 "sudo /opt/shv-prod/install.sh"

  environment:
    name: jessie

production-deploy-heaven:
  only:
    - production
  tags:
    - linux
  stage:
    deploy
  script:
    - id
    - cd build
    - rsync -avz lib bin shv@138.68.112.73:/opt/shv/production/
    - ssh -t shv@138.68.112.73 "sudo /opt/shv/production/install.sh"
  environment:
    name: heaven

test-deploy:
  only:
    - master
  tags:
    - linux
  stage:
    deploy
  script:
    # nirvana
    - pwd
    - rsync -avz shvbroker/etc gitlab@165.227.247.202:/opt/shv/ 
    - rsync -avz clients/hscope/etc gitlab@165.227.247.202:/opt/shv/ 
    - cd build
    - rsync -avz lib bin /opt/shv/ 
    - rsync -avz lib bin gitlab@165.227.247.202:/opt/shv/ 
    - ssh -t gitlab@165.227.247.202 "sudo /opt/shv/install.sh"

  environment:
    name: jessie

win-build:
  tags:
    - windows
  stage:
    build
  script: 
    - bash build-win.sh
  artifacts:
    paths:
      - _inno/

win-deploy:
  only:
    - production
  tags:
    - windows
  stage:
    deploy
  script:
    - cmd /Q /C deploy-win.sh
  environment:
    name: claudius

