variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

linux:
  tags:
    - linux
  stage:
    build
  artifacts:
    paths:
    - build/
  script:
    #- git submodule update --init --force --recursive
    - rm -rf build
    - mkdir -p build
    - cd build
    - /opt/qt/5.8/gcc_64/bin/qmake -r CONFIG+=no-libshv-gui ../shv.pro DEFINES+=GIT_COMMIT=${CI_BUILD_REF}
    - make -j2

linux-deploy:
  only:
    - production
  tags:
    - linux
  stage:
    deploy
  script:
    - id
    - cd build
    # aws
    - rsync -avz lib bin gitlab-jessie@35.167.83.38:/opt/shv/ 
    - ssh -t gitlab-jessie@35.167.83.38 "sudo /opt/shv/install.sh"
    # nirvana
    - rsync -avz lib bin gitlab@165.227.247.202:/opt/shv/ 
    - ssh -t gitlab@165.227.247.202 "sudo /opt/shv/install.sh"

  environment:
    name: jessie

win-build:
  tags:
    - windows
  stage:
    build
  script:
    - cmd /Q /C build-win.cmd
  artifacts:
    paths:
      - _inno/

win-deploy:
  only:
    - master
    - windows-build
  tags:
    - windows
  stage:
    deploy
  script:
    - cmd /Q /C deploy-win.cmd
  environment:
    name: claudius

